### PR TITLE
fix: display 10 entries per page in rep history

### LINKED ISSUE #212: `!history` errors because each message page is now much longer
Because we have links in every record, the page is probably three times longer than before. We need to lower the number of records on each page.

### PR DESCRIPTION
**Pull request by Josh-Cena**
Fix #212

Each entry is now about 150 characters long, so 10 seems safer

### CODE REVIEW

File: src/modules/rep.ts [hunk 1]
```diff
@@ -181,19 +181,19 @@ export class RepModule extends Module {
 					rg.amount
 				} ${emoji}** on [message](${messageLink}) (<@${
 					rg.initialGiver
-				}>${rg.amount > 1 ? ' et al.' : ''}) at <t:${
-					(+new Date(rg.date) / 1000) | 0
-				}>`;
+				}>${rg.amount > 1 ? ' et al.' : ''}) at <t:${Math.floor(
+					+new Date(rg.date) / 1000,
+				)}>`;
```
Comment (tjjfvi) [inline src/modules/rep.ts:186]: *Fiiine*

**Review by tjjfvi — APPROVED** [review]

File: src/modules/rep.ts (hunk 1 above)
Comment (Josh-Cena) [reply src/modules/rep.ts:186]: _What if the bot is in use after year 2106?_

**Comment by orta** [comment]
Looks reasonable to me

**Review by orta — APPROVED** [review]
